import { Inter } from "next/font/google";
import { ConfigProvider, Layout } from "antd";
import HomeLayout from "../components/HomeLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home({ children }) {
  return <HomeLayout>{children}</HomeLayout>;
}
