import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import { ConfigProvider, Layout } from "antd";
import { Content, Header } from "antd/es/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ConfigProvider theme={{
        token:{
          colorPrimary:"#FB3F6C",
          colorBgBase:"#121212",
          colorText:"white",
          colorLinkActive:"white",
          colorBgTextActive:"121212"
        }
      }} >
      <body className={inter.className}>
        <Layout>
          <SideBar />
          <Layout>
            <Header className="bg-header"></Header>
            <Content className="bg-panel">
            {children}
            </Content>
          </Layout>
        </Layout>
      </body>
      </ConfigProvider>
    </html>
  );
}
