import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider, Layout } from "antd";
import HomeLayout from "./components/HomeLayout";
import AuthProvider from "@/context/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#FB3F6C",
            colorBgBase: "#121212",
            colorText: "white",
            colorLinkActive: "white",
            colorBgTextActive: "121212",
          },
        }}
      >
        <AuthProvider>
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </ConfigProvider>
    </html>
  );
}
